[package]
name = "joel_chirayath"
version = "0.0.0"
edition = "2021"
authors = ["joel.chiryath@sa.stud.vu.lt"]

[dependencies]
thiserror = "1.0"  # For clean error handling
log = "0.4"        # For logging/debugging

[dev-dependencies]
pretty_assertions = "1.4"  # Better diffs in test failures
